# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/railway/Desktop/大创/UI/newMain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(667, 561)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_DataAnalysis = QtWidgets.QPushButton(self.MainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DataAnalysis.sizePolicy().hasHeightForWidth())
        self.pushButton_DataAnalysis.setSizePolicy(sizePolicy)
        self.pushButton_DataAnalysis.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_DataAnalysis.setStyleSheet("")
        self.pushButton_DataAnalysis.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/DataAnalysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DataAnalysis.setIcon(icon)
        self.pushButton_DataAnalysis.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_DataAnalysis.setCheckable(False)
        self.pushButton_DataAnalysis.setObjectName("pushButton_DataAnalysis")
        self.gridLayout_2.addWidget(self.pushButton_DataAnalysis, 0, 0, 1, 1)
        self.pushButton_Platform = QtWidgets.QPushButton(self.MainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Platform.sizePolicy().hasHeightForWidth())
        self.pushButton_Platform.setSizePolicy(sizePolicy)
        self.pushButton_Platform.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/platform.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Platform.setIcon(icon1)
        self.pushButton_Platform.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_Platform.setObjectName("pushButton_Platform")
        self.gridLayout_2.addWidget(self.pushButton_Platform, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.MainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.MainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.MainPage)
        self.DataAnalysisPage = QtWidgets.QWidget()
        self.DataAnalysisPage.setObjectName("DataAnalysisPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DataAnalysisPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonReturn = QtWidgets.QPushButton(self.DataAnalysisPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReturn.sizePolicy().hasHeightForWidth())
        self.pushButtonReturn.setSizePolicy(sizePolicy)
        self.pushButtonReturn.setStyleSheet("#pushButtonReturn{background:rgba(255, 255, 255, 0)}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/image/Return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonReturn.setIcon(icon2)
        self.pushButtonReturn.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonReturn.setObjectName("pushButtonReturn")
        self.horizontalLayout.addWidget(self.pushButtonReturn)
        self.DataAddress = QtWidgets.QPlainTextEdit(self.DataAnalysisPage)
        self.DataAddress.setMaximumSize(QtCore.QSize(16777215, 28))
        self.DataAddress.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataAddress.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataAddress.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.DataAddress.setPlainText("")
        self.DataAddress.setObjectName("DataAddress")
        self.horizontalLayout.addWidget(self.DataAddress)
        self.DataFile = QtWidgets.QPushButton(self.DataAnalysisPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataFile.sizePolicy().hasHeightForWidth())
        self.DataFile.setSizePolicy(sizePolicy)
        self.DataFile.setObjectName("DataFile")
        self.horizontalLayout.addWidget(self.DataFile)
        self.DataFormat = QtWidgets.QComboBox(self.DataAnalysisPage)
        self.DataFormat.setFrame(True)
        self.DataFormat.setObjectName("DataFormat")
        self.DataFormat.addItem("")
        self.DataFormat.addItem("")
        self.DataFormat.addItem("")
        self.horizontalLayout.addWidget(self.DataFormat)
        self.StartAnalysis = QtWidgets.QPushButton(self.DataAnalysisPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartAnalysis.sizePolicy().hasHeightForWidth())
        self.StartAnalysis.setSizePolicy(sizePolicy)
        self.StartAnalysis.setObjectName("StartAnalysis")
        self.horizontalLayout.addWidget(self.StartAnalysis)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(538, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.replaceLayout = QtWidgets.QVBoxLayout()
        self.replaceLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.replaceLayout.setObjectName("replaceLayout")
        self.verticalLayout.addLayout(self.replaceLayout)
        self.ReplaceWidget = QtWidgets.QWidget(self.DataAnalysisPage)
        self.ReplaceWidget.setObjectName("ReplaceWidget")
        self.verticalLayout.addWidget(self.ReplaceWidget)
        self.stackedWidget.addWidget(self.DataAnalysisPage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setSeparatorsCollapsible(False)
        self.menuopen.setToolTipsVisible(False)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionDeepBlack = QtWidgets.QAction(MainWindow)
        self.actionDeepBlack.setObjectName("actionDeepBlack")
        self.actionMetroUI = QtWidgets.QAction(MainWindow)
        self.actionMetroUI.setObjectName("actionMetroUI")
        self.actionHide = QtWidgets.QAction(MainWindow)
        self.actionHide.setObjectName("actionHide")
        self.actionShow = QtWidgets.QAction(MainWindow)
        self.actionShow.setObjectName("actionShow")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionHide)
        self.menu.addAction(self.actionShow)
        self.menuopen.addAction(self.actionDefault)
        self.menuopen.addAction(self.actionBlack)
        self.menuopen.addAction(self.actionDeepBlack)
        self.menuopen.addAction(self.actionMetroUI)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuopen.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.actionHide.triggered.connect(self.centralwidget.close)
        self.actionShow.triggered.connect(self.centralwidget.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_DataAnalysis.setToolTip(_translate("MainWindow", "<html><head/><body><p>数据分析</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButtonReturn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>返回</p></body></html>"))
        self.DataFile.setText(_translate("MainWindow", "选择数据"))
        self.DataFormat.setItemText(0, _translate("MainWindow", "Liar data"))
        self.DataFormat.setItemText(1, _translate("MainWindow", "Signalmedia-1m"))
        self.DataFormat.setItemText(2, _translate("MainWindow", "FeverData"))
        self.StartAnalysis.setText(_translate("MainWindow", "开始"))
        self.menu.setTitle(_translate("MainWindow", "选项"))
        self.menuopen.setTitle(_translate("MainWindow", "Theme"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionDeepBlack.setText(_translate("MainWindow", "DeepBlack"))
        self.actionMetroUI.setText(_translate("MainWindow", "MetroUI"))
        self.actionHide.setText(_translate("MainWindow", "Hide"))
        self.actionShow.setText(_translate("MainWindow", "Show"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))

import source_rc
